# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='reports',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='reports',
            name='outstanding',
            field=models.CharField(choices=[('RACISM', 'racism'), ('BAD-SERVICES', 'Bad-Services'), ('BRIBERY', 'Bribery')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='institution_category',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], max_length=60),
        ),
    ]
