# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0002_auto_20180807_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
