# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_app', '0004_auto_20180807_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.CharField(choices=[('MAYOR_ROAD', 'Mayor_Road'), ('RONGAI', 'rongai'), ('GATAKA', 'gataka'), ('OLOLUA', 'ololua')], max_length=60),
        ),
    ]
